// <auto-generated />
using Brigade.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Brigade.Admin.Data.Sqlite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423213622_AddModelOptionsFields")]
    partial class AddModelOptionsFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("AgentOptionsMcpServerOptions", b =>
                {
                    b.Property<int>("AgentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McpServersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentsId", "McpServersId");

                    b.HasIndex("McpServersId");

                    b.ToTable("AgentMcpServers", (string)null);
                });

            modelBuilder.Entity("AgentOptionsMiddlewareOptions", b =>
                {
                    b.Property<int>("AgentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MiddlewareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentsId", "MiddlewareId");

                    b.HasIndex("MiddlewareId");

                    b.ToTable("AgentMiddleware", (string)null);
                });

            modelBuilder.Entity("AgentOptionsModelOptions", b =>
                {
                    b.Property<int>("AgentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentsId", "ModelsId");

                    b.HasIndex("ModelsId");

                    b.ToTable("AgentModels", (string)null);
                });

            modelBuilder.Entity("AgentOptionsSkillOptions", b =>
                {
                    b.Property<int>("AgentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("AgentSkills", (string)null);
                });

            modelBuilder.Entity("AgentOptionsToolOptions", b =>
                {
                    b.Property<int>("AgentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentsId", "ToolsId");

                    b.HasIndex("ToolsId");

                    b.ToTable("AgentTools", (string)null);
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.AgentOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.McpServerHeaders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("McpServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("McpServerId");

                    b.ToTable("McpServerHeaders");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.McpServerOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Transport")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mcps");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.MemoryOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionToolDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionToolName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxResults")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.MiddlewareOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Middlewares");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.SkillOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedTools")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compatibility")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resources")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scripts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.ToolOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersSchema")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.WorkflowOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Providers.ModelOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CachedTokenCost")
                        .HasColumnType("REAL");

                    b.Property<int>("ContextWindowSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<double>("InputTokenCost")
                        .HasColumnType("REAL");

                    b.Property<string>("KnowledgeCutoff")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("OutputTokenCost")
                        .HasColumnType("REAL");

                    b.Property<bool>("SupportsAudio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsCodeExecution")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsDistillation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsFileSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsFineTuning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsFunctionCalling")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsImage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsMCP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsStructuredOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsText")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsToolUse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsVideo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsWebSearch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Providers.ProviderOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("ModelOptionsProviderOptions", b =>
                {
                    b.Property<int>("ModelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProvidersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModelsId", "ProvidersId");

                    b.HasIndex("ProvidersId");

                    b.ToTable("ProviderModels", (string)null);
                });

            modelBuilder.Entity("AgentOptionsMcpServerOptions", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brigade.Admin.Data.Models.Agents.McpServerOptions", null)
                        .WithMany()
                        .HasForeignKey("McpServersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentOptionsMiddlewareOptions", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brigade.Admin.Data.Models.Agents.MiddlewareOptions", null)
                        .WithMany()
                        .HasForeignKey("MiddlewareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentOptionsModelOptions", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brigade.Admin.Data.Models.Providers.ModelOptions", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentOptionsSkillOptions", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brigade.Admin.Data.Models.Agents.SkillOptions", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentOptionsToolOptions", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brigade.Admin.Data.Models.Agents.ToolOptions", null)
                        .WithMany()
                        .HasForeignKey("ToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.AgentOptions", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Providers.ProviderOptions", "Provider")
                        .WithMany("Agents")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.McpServerHeaders", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Agents.McpServerOptions", "McpServer")
                        .WithMany("Headers")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.MemoryOptions", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Agents.AgentOptions", "Agent")
                        .WithOne("Memory")
                        .HasForeignKey("Brigade.Admin.Data.Models.Agents.MemoryOptions", "AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("ModelOptionsProviderOptions", b =>
                {
                    b.HasOne("Brigade.Admin.Data.Models.Providers.ModelOptions", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brigade.Admin.Data.Models.Providers.ProviderOptions", null)
                        .WithMany()
                        .HasForeignKey("ProvidersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.AgentOptions", b =>
                {
                    b.Navigation("Memory");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Agents.McpServerOptions", b =>
                {
                    b.Navigation("Headers");
                });

            modelBuilder.Entity("Brigade.Admin.Data.Models.Providers.ProviderOptions", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
