<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\libs\Brigade.Admin.Data\Brigade.Admin.Data.csproj" />
    <ProjectReference Include="..\..\src\libs\Brigade.Admin.Data.Sqlite\Brigade.Admin.Data.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Brigade.Agents\Brigade.Agents.csproj" />
  </ItemGroup>
</Project>
