CREATE DATABASE brigade;

GRANT ALL PRIVILEGES ON DATABASE brigade TO postgres;

CREATE USER brigade WITH PASSWORD 'brigade';

GRANT ALL PRIVILEGES ON DATABASE brigade TO brigade;

\c brigade

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto VERSION '1.4';
