<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legion.Admin.Data\Legion.Admin.Data.csproj" />
    <ProjectReference Include="..\Legion.Admin.Data.Models\Legion.Admin.Data.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.Abstractions" />
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="OpenIddict.Core" />
    <PackageReference Include="OpenIddict.Server" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Radzen.Blazor" />
  </ItemGroup>
</Project>
