// <auto-generated />
using System;
using Legion.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Legion.Admin.Data.Sqlite.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502152359_AddPromptLibrary")]
    partial class AddPromptLibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("AgentOptionsMcpServerOptions", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("McpServersId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "McpServersId");

                    b.HasIndex("McpServersId");

                    b.ToTable("AgentMcpServers", "agents");
                });

            modelBuilder.Entity("AgentOptionsMiddlewareOptions", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MiddlewareId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "MiddlewareId");

                    b.HasIndex("MiddlewareId");

                    b.ToTable("AgentMiddleware", "agents");
                });

            modelBuilder.Entity("AgentOptionsModelOptions", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "ModelsId");

                    b.HasIndex("ModelsId");

                    b.ToTable("AgentModels", "agents");
                });

            modelBuilder.Entity("AgentOptionsSkillOptions", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("AgentSkills", "agents");
                });

            modelBuilder.Entity("AgentOptionsToolOptions", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToolsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "ToolsId");

                    b.HasIndex("ToolsId");

                    b.ToTable("AgentTools", "agents");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.AgentOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Agents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AgentOptions");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.McpServerHeaders", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("McpServerId");

                    b.ToTable("McpServerHeaders");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.McpServerOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Transport")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("McpServers", "agents");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.MemoryOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionToolDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionToolName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxResults")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.MiddlewareOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Middlewares");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.SkillOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedTools")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compatibility")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resources")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scripts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.ToolOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersSchema")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.WorkflowOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Prompts.AgentPromptAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("AgentId", "DefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_prompt_assignments_agent_definition");

                    b.ToTable("AgentPromptAssignments");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Prompts.PromptDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefaultIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_definitions_path");

                    b.ToTable("PromptDefinitions");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Prompts.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frontmatter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_versions_definition_published")
                        .HasFilter("\"Status\" = 'Published'");

                    b.ToTable("PromptVersions");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Providers.ModelOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("CachedTokenCost")
                        .HasColumnType("REAL");

                    b.Property<int>("ContextWindowSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<double>("InputTokenCost")
                        .HasColumnType("REAL");

                    b.Property<string>("KnowledgeCutoff")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("OutputTokenCost")
                        .HasColumnType("REAL");

                    b.Property<bool>("SupportsAudio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsCodeExecution")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsDistillation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsFileSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsFineTuning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsFunctionCalling")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsImage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsMCP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsStructuredOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsText")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsToolUse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsVideo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsWebSearch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Providers.ProviderOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Providers", "agents");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.SecretOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("ModelOptionsProviderOptions", b =>
                {
                    b.Property<Guid>("ModelsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProvidersId")
                        .HasColumnType("TEXT");

                    b.HasKey("ModelsId", "ProvidersId");

                    b.HasIndex("ProvidersId");

                    b.ToTable("ProviderModels", "agents");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.AgentTemplate", b =>
                {
                    b.HasBaseType("Legion.Admin.Data.Models.Agents.AgentOptions");

                    b.Property<string>("TemplateDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("AgentTemplate");
                });

            modelBuilder.Entity("AgentOptionsMcpServerOptions", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Legion.Admin.Data.Models.Agents.McpServerOptions", null)
                        .WithMany()
                        .HasForeignKey("McpServersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentOptionsMiddlewareOptions", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Legion.Admin.Data.Models.Agents.MiddlewareOptions", null)
                        .WithMany()
                        .HasForeignKey("MiddlewareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentOptionsModelOptions", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Legion.Admin.Data.Models.Providers.ModelOptions", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentOptionsSkillOptions", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Legion.Admin.Data.Models.Agents.SkillOptions", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentOptionsToolOptions", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Legion.Admin.Data.Models.Agents.ToolOptions", null)
                        .WithMany()
                        .HasForeignKey("ToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.AgentOptions", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Providers.ProviderOptions", "Provider")
                        .WithMany("Agents")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.McpServerHeaders", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Agents.McpServerOptions", "McpServer")
                        .WithMany("Headers")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.MemoryOptions", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Agents.AgentOptions", "Agent")
                        .WithOne("Memory")
                        .HasForeignKey("Legion.Admin.Data.Models.Agents.MemoryOptions", "AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Prompts.AgentPromptAssignment", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Agents.AgentOptions", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Legion.Admin.Data.Models.Prompts.PromptDefinition", "Definition")
                        .WithMany("Assignments")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Prompts.PromptVersion", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Prompts.PromptDefinition", "Definition")
                        .WithMany("Versions")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("ModelOptionsProviderOptions", b =>
                {
                    b.HasOne("Legion.Admin.Data.Models.Providers.ModelOptions", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Legion.Admin.Data.Models.Providers.ProviderOptions", null)
                        .WithMany()
                        .HasForeignKey("ProvidersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.AgentOptions", b =>
                {
                    b.Navigation("Memory");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Agents.McpServerOptions", b =>
                {
                    b.Navigation("Headers");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Prompts.PromptDefinition", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Legion.Admin.Data.Models.Providers.ProviderOptions", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
