CREATE DATABASE legion;

GRANT ALL PRIVILEGES ON DATABASE legion TO postgres;

CREATE USER legion WITH PASSWORD 'legion';

GRANT ALL PRIVILEGES ON DATABASE legion TO legion;

\c legion

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto VERSION '1.4';
